spring:
  application:
    name=SpringAI_Gemini_OpenAI
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
gemini:
  api-key: ${GOOGLE_API_KEY}
  base-url: https://generativelanguage.googleapis.com/v1beta/openai/
  completion-path: chat/completions
  model: gemini-2.0-flash
  temperature: 0.7

